### ISSUE TITLE
Quiet output during deploy publish

### ISSUE THREAD

**Issue by glinton** [nanobox-io/nanobox-docker-build#128]
[In the publish hook](https://github.com/nanobox-io/nanobox-docker-build/blob/master/files/opt/nanobox/hooks/publish#L75) we pass the `-v` to rsync, can we make this conditional somehow, defaulting to off? It is currently only shown during `nanobox -v` or in ci mode. We have had issues with travisCI complaining that the log is too long (limit 10k lines).

**Comment by tylerflint** [comment]
I'm not sure that your assumption is correct. The `-v` was put there intentionally so that during the summarized mode, they can see which files are being synced. If this is removed, there will not be any indication of what's happening during a subsequent deploy. Adding the `-v` was intentional to provide visibility. 

That said, we can certainly address the reality that -v during ci mode is problematic, but we also need to ensure that normal deploys are verbose.

**Comment by glinton** [comment]
Good call, i'll make it conditional on an env var. `QUIET_SYNC=true`

**Comment by glinton** [comment]
As @sanderson brought up in slack, this should be a `nanobox config` setting

Something like `nanobox config set ci-quiet-sync true`

**Comment by sanderson** [comment]
Suggestion, since this setting should be unique to the CI workflow, I think the actual config should be: `ci-quite-sync`

**Comment by glinton** [comment]
Official 4 person slack decision: if ci-mode is true, quiet by default. `nb config ci-sync-verbose true` to turn on debugging
